# -*- coding: utf-8 -*-
"""datripdata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RkCWfnLzio3pPX9GQuoaWMzdOfDxcNG1
"""

# Dataset load
import pandas as pd
url = 'https://s3.amazonaws.com/capitalbikeshare-data/201908-capitalbikeshare-tripdata.zip'
df = pd.read_csv(url, compression='zip')
print(df.columns)

# Preprocessing
df.dropna(inplace=True)
df.columns = ['duration', 'start_date', 'end_date', 'start_station_number', 'start_station', 'end_station_number', 'end_station', 'bike_number', 'class']
print(df.shape)
df.head()

# Train test split
import numpy as np
from sklearn import model_selection
X = np.array(df[['duration', 'start_station_number', 'end_station_number']])
Y = np.array(df['class'])
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.2)

# Training the classifier
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier()
clf.fit(X_train, Y_train)

# Result and report
from sklearn.metrics import classification_report
predictions = clf.predict(X_test)
print(classification_report(Y_test, predictions))
print(predictions[:10])
print(Y_test[:10])