# -*- coding: utf-8 -*-
"""data_analytics_a2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10PxGIhjQr4RJbjwhWleAH3r_v7hBm86s
"""

# Upload data
from google.colab import files
files.upload()

import pandas as pd
df = pd.read_csv('dataset.csv')
df.describe()

import matplotlib.pyplot as plt
df.hist(figsize=(10,10))
plt.show()

import numpy as np
from sklearn import model_selection
X = np.array(df.drop(['Outcome'], 1))
Y = np.array(df['Outcome'])
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.2)

from sklearn.metrics import classification_report, accuracy_score
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()

clf.fit(X_train, Y_train)

predictions = clf.predict(X_test)

print(accuracy_score(Y_test, predictions))
print(classification_report(Y_test, predictions))